[workspace]
members = ["datachannel-facade", "libdatachannel", "libdatachannel-sys", "web-datachannel"]

[package]
name = "dachannel"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
async-channel = "2"
async-lock = "3"
datachannel-facade = { path = "datachannel-facade" }
oneshot = "0.1"
thiserror = "1"
