[workspace]
members = ["datachannel-facade", "libdatachannel", "libdatachannel-sys", "web-datachannel"]

[package]
name = "dachannel"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
