[workspace]
members = ["datachannel-facade", "libdatachannel", "libdatachannel-sys", "web-datachannel"]

[package]
name = "dachannel"
version = "0.1.0"
edition = "2021"
license = "MIT"

[features]
default = ["server"]
server = ["dep:hyper", "dep:tokio"]

[dependencies]
async-channel = "2"
async-lock = "3"
datachannel-facade = { path = "datachannel-facade" }
oneshot = "0.1"
thiserror = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
hyper = { version = "1", optional = true }
tokio = { version = "1", optional = true, features = ["full"] }

[dev-dependencies]
cfg-if = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
pollster = { version = "0.3", features = ["macro"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"
