[package]
name = "simple-server"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
dachannel = { path = "../..", features = ["server"] }
tokio = { version = "1", features = ["full"] }
