[package]
name = "libdatachannel"
version = "0.0.0"
edition = "2021"
license = "MIT"

[dependencies]
log = "0.4"
libdatachannel-sys = { path = "../libdatachannel-sys" }
num-derive = "0.4"
num-traits = "0.2"
thiserror = "1"

[dev-dependencies]
test-log = "0.2"
