[package]
name = "simple-echo-client"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
dachannel = { path = "../.." }
dachannel-client = { path = "../../dachannel-client" }
tokio = { version = "1", features = ["full"] }
