[package]
name = "libdatachannel-sys"
version = "0.20.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/coevolutions/dachannel"

[build-dependencies]
bindgen = "0.69"
cmake = "0.1"
cpp_build = "0.5"
openssl-src = "300"
