[package]
name = "datachannel-facade"
version = "0.0.0"
edition = "2021"
license = "MIT"

[dependencies]
log = "0.4"
thiserror = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libdatachannel = { path = "../libdatachannel" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-datachannel = { path = "../web-datachannel" }

[dev-dependencies]
async-channel = "2"
async-notify = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
pollster = { version = "0.3", features = ["macro"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"
